# Generated by Django 2.0.2 on 2018-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryregistration',
            name='command_prefix',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='repositoryregistration',
            name='container_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='repositoryregistration',
            name='repository_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='repositoryregistration',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
