# Generated by Django 2.0.2 on 2018-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0002_auto_20180317_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryregistration',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
