# Generated by Django 2.0.2 on 2018-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Container', '0002_auto_20180523_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='endpoint_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
