# Generated by Django 2.0.5 on 2018-05-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Container', '0003_container_endpoint_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndPoint',
        ),
    ]
